# This file defines various default values used by server policies 
# These values typically do not need to changes but can be modified depending on customer deployments

# BIOS policies
description_of_m8_bios_policy : "BIOS Policy for Performance Optimized {{ server_cpu_type }}-based M8 Servers"
description_of_m7_bios_policy : "BIOS Policy for Performance Optimized Intel-based M7 Servers"
description_of_m6_bios_policy : "BIOS Policy for Performance Optimized {{ server_cpu_type }}-based M6 Servers"

# IMC Access Policy
description_of_imc_access_policy    : "IMC Access Policy for KVM Access"

# KVM Policy
description_of_kvm_policy           : "KVM Policy to set Tunneled KVM to {{enable_tunneled_kvm}}"

# vMedia Policy
description_of_vmedia_policy        : "vMedia Policy to enable KVM mounted DVDs"

# M.2 Boot Order Policy
m2_boot_order_policy_description    : "M.2 Boot Order Policy"

# Server Power Policy
server_power_policy_description     : "Default Server Power Policy for X- and B-Series Blades"

# Server Thermal Policy
server_thermal_policy_description     : "Default Server Thermal Policy for C-Series Rack Mounts"

# IPMI over LAN Policy 
description_of_ipmi_policy          : "Enable IPMI over LAN"

# Local User Policy to enable KVM Access 
description_of_LocalUser_policy      : "Allow Local Users in this policy KVM Access to Servers"

# M.2 RAID Storage Policie
description_of_m2_raid_policy              : "M.2 RAID Policy for better M.2 RAID Performance"

# MTU 1500 Ethernet QoS Policy
description_of_mtu1500_eth_qos_policy   : "Ethernet QoS Policy setting MTU to 1500 and priority to Best Effort"
mtu1500                              : 1500

# MTU 9000 Ethernet QoS Policy
description_of_mtu9000_eth_qos_policy   : "Ethernet QoS Policy setting MTU to 9000 and priority to Best Effort"
mtu9000                              : 9000

# Remaining QoS Policy Parameters
class_of_service                     : 0
burst                                : 10240
priority                             : "Best Effort"
rate_limit                           : 100000

# Ethernet Network Control Policy
description_of_ethernet_network_control_policy  : "Ethernet Network Control Policy to enable CDP and LLDP"

# Linux-V2 Ethernet Adapter Policy for CoreOS
description_of_ethernet_adapter_linuxv2_policy  : "Ethernet Adapter Policy for CoreOS - Linux-V2 for eno5 BareMetal-MGMT Interface"

# Ethernet Adapter Policy for CoreOS 16 Rx Queues - (Applies to Storage and VM Interfaces)
# If using only 5G VICs, ring_size parameters can be increased up to 16384.
description_of_ethernet_adapter_16rxq_policy  : "Ethernet Adapter Policy for 16Rx Queues"
number_of_interrupts    : 19
receive_queue_count     : 16
receive_ring_size       : 4096
transmit_queue_count    : 1
transmit_ring_size      : 4096
completion_queue_count  : 17
completion_ring_size    : 1

# Ethernet Network Group Policy - VLAN details of vNIC assigned for BareMetal-MGMT VLAN
description_of_network_group_policy_for_management  : "VLAN details of eno5 interface to allow BareMetal-MGMT traffic; BareMetal-MGMT VLAN set as Native VLAN"

# Ethernet Network Group Policy - VLAN details of vNIC assigned for OCP iSCSI-A and NVMe-TCP-A VLANs
description_of_network_group_policy_for_iscsi_nvme_tcp_a       : "VLAN details of vNIC assigned for OCP iSCSI-A VLAN and optional NVMe-TCP-A VLAN; iSCSI-A VLAN set as Native VLAN"

# Ethernet Network Group Policy - VLAN details of vNIC assigned for OCP iSCSI-B and NVMe-TCP-B VLANs
description_of_network_group_policy_for_iscsi_nvme_tcp_b       : "VLAN details of vNIC assigned for OCP iSCSI-B VLAN and optional NVMe-TCP-B VLAN; iSCSI-B VLAN set as Native VLAN"

# Ethernet Network Group Policy - VLAN details of OCP NFS vNIC Interface
description_of_network_group_policy_for_nfs        : "VLAN details of vNIC assigned for OCP NFS vNIC Interface; BareMetal-MGMT VLAN set as Native VLAN"

# vNIC Template for BareMetal-MGMT
description_of_vnic_template_baremetal      : "vNIC Template for Node BareMetal-MGMT vNIC; BareMetal-MGMT VLAN set as Native VLAN"

# vNIC Template for iSCSI-NVMe-TCP-A
description_of_vnic_template_iscsi_nvme_tcp_a      : "vNIC Template for Node iSCSI-NVMe-TCP-A vNIC; iSCSI-A VLAN set as Native VLAN"

# vNIC Template for iSCSI-NVMe-TCP-B
description_of_vnic_template_iscsi_nvme_tcp_b      : "vNIC Template for Node iSCSI-NVMe-TCP-B vNIC; iSCSI-B VLAN set as Native VLAN"

# vNIC Template for NFS
description_of_vnic_template_nfs      : "vNIC Template for Node NFS vNIC; NFS VLAN set as Native VLAN"

# LAN Connectivity Policies
description_of_cp_lan_connectivity_policy         : "LAN Connectivity Policy for OpenShift Control Plane Nodes"
description_of_worker_lan_connectivity_policy     : "LAN Connectivity Policy for OpenShift Worker Nodes"