---
- name: "Configure M.2 RAID Storage Policy"
  vars:
    api_info: &api_info
      api_private_key: "{{ api_private_key }}"
      api_key_id: "{{ api_key_id }}"
      api_uri: "{{ api_uri | default(omit) }}"
      validate_certs: "{{ validate_certs | default(omit) }}"
      state: "{{ state | default(omit) }}"

  cisco.intersight.intersight_rest_api:
    <<: *api_info
    resource_path: /storage/StoragePolicies
    query_params:
       $filter: "Name eq '{{ name_of_m2_raid_policy }}'"
    api_body: {
        "Name": "{{ name_of_m2_raid_policy }}",
        "Description": "{{ description_of_m2_raid_policy }}",
        "DefaultDriveMode": "UnconfiguredGood",
        "DirectAttachedNvmeSlots": "",
        "M2VirtualDrive": {
           "ControllerSlot": "MSTOR-RAID-1",
           "Enable": true,
           "Name": "MStorBootVd"
          },
        "Raid0Drive": {
           "Enable": false
          },
        "Organization": {
           "Moid": "{{ intersight_org.api_response.Moid }}"
         },
        "RaidAttachedNvmeSlots": "",
        "UnusedDisksState": "NoChange",
        "UseJbodForVdCreation": false,
        Tags: [{Key: "configmode", Value: "ansible"},{Key: "prefix", Value: "{{ prefix }}"}]
     }
  register: m2_raid_policy
