---
- name: "Configure Ethernet Network Group Policy for BareMetal-MGMT"
  vars:
    api_info: &api_info_mgmt
      api_private_key: "{{ api_private_key }}"
      api_key_id: "{{ api_key_id }}"
      api_uri: "{{ api_uri | default(omit) }}"
      validate_certs: "{{ validate_certs | default(omit) }}"
      state: "{{ state | default(omit) }}"

  cisco.intersight.intersight_rest_api:
    <<: *api_info_mgmt
    resource_path: /fabric/EthNetworkGroupPolicies
    query_params:
       $filter: "Name eq '{{ name_of_network_group_policy_for_management }}'"
    api_body: {
      "Name": "{{ name_of_network_group_policy_for_management }}",
      "Description": "{{ description_of_network_group_policy_for_management }}",

      "Organization": {
         "Moid": "{{ intersight_org.api_response.Moid }}"
       },
      Tags: [{Key: "configmode", Value: "ansible"},{Key: "prefix", Value: "{{ prefix }}"}],
      "VlanSettings": {
         "NativeVlan": "{{ baremetal_vlan_id }}",
         "AllowedVlans": "{{ baremetal_vlan_id|int }}"
         }
      }
  register: management_network_group_policy

- name: "Configure Ethernet Network Group Policy for iSCSI-A"
  vars:
    api_info: &api_info_iscsi_a
      api_private_key: "{{ api_private_key }}"
      api_key_id: "{{ api_key_id }}"
      api_uri: "{{ api_uri | default(omit) }}"
      validate_certs: "{{ validate_certs | default(omit) }}"
      state: "{{ state | default(omit) }}"

  cisco.intersight.intersight_rest_api:
    <<: *api_info_iscsi_a
    resource_path: /fabric/EthNetworkGroupPolicies
    query_params:
       $filter: "Name eq '{{ name_of_network_group_policy_for_iscsi_nvme_tcp_a }}'"
    api_body: {
      "Name": "{{ name_of_network_group_policy_for_iscsi_nvme_tcp_a }}",
      "Description": "{{ description_of_network_group_policy_for_iscsi_nvme_tcp_a }}",

      "Organization": {
         "Moid": "{{ intersight_org.api_response.Moid }}"
       },
      Tags: [{Key: "configmode", Value: "ansible"},{Key: "prefix", Value: "{{ prefix }}"}],
      "VlanSettings": {
         "NativeVlan": "{{ iscsiA_vlan_id }}",
         "AllowedVlans": "{{ iscsiA_vlan_id|int }}"
         }
      }
  register: iscsi_nvme_a_network_group_policy

- name: "Add NVMe-TCP-A VLAN to iSCSI-NVMe-TCP-A Network Group Policy"
  vars:
    api_info: &api_info_iscsi_a_w_nvme_tcp_a
      api_private_key: "{{ api_private_key }}"
      api_key_id: "{{ api_key_id }}"
      api_uri: "{{ api_uri | default(omit) }}"
      validate_certs: "{{ validate_certs | default(omit) }}"
      state: "{{ state | default(omit) }}"

  cisco.intersight.intersight_rest_api:
    <<: *api_info_iscsi_a_w_nvme_tcp_a
    resource_path: /fabric/EthNetworkGroupPolicies
    query_params:
       $filter: "Name eq '{{ name_of_network_group_policy_for_iscsi_nvme_tcp_a }}'"
    api_body: {
      "Name": "{{ name_of_network_group_policy_for_iscsi_nvme_tcp_a }}",
      "Description": "{{ description_of_network_group_policy_for_iscsi_nvme_tcp_a }}",

      "Organization": {
         "Moid": "{{ intersight_org.api_response.Moid }}"
       },
      Tags: [{Key: "configmode", Value: "ansible"},{Key: "prefix", Value: "{{ prefix }}"}],
      "VlanSettings": {
         "NativeVlan": "{{ iscsiA_vlan_id }}",
         "AllowedVlans": "{{ iscsiA_vlan_id }},{{ nvme_tcpA_vlan_id }}"
         }
      }
  when: configure_nvme_tcp == 'true'

- name: "Configure Ethernet Network Group Policy for iSCSI-B"
  vars:
    api_info: &api_info_iscsi_b
      api_private_key: "{{ api_private_key }}"
      api_key_id: "{{ api_key_id }}"
      api_uri: "{{ api_uri | default(omit) }}"
      validate_certs: "{{ validate_certs | default(omit) }}"
      state: "{{ state | default(omit) }}"

  cisco.intersight.intersight_rest_api:
    <<: *api_info_iscsi_b
    resource_path: /fabric/EthNetworkGroupPolicies
    query_params:
       $filter: "Name eq '{{ name_of_network_group_policy_for_iscsi_nvme_tcp_b }}'"
    api_body: {
      "Name": "{{ name_of_network_group_policy_for_iscsi_nvme_tcp_b }}",
      "Description": "{{ description_of_network_group_policy_for_iscsi_nvme_tcp_b }}",

      "Organization": {
         "Moid": "{{ intersight_org.api_response.Moid }}"
       },
      Tags: [{Key: "configmode", Value: "ansible"},{Key: "prefix", Value: "{{ prefix }}"}],
      "VlanSettings": {
         "NativeVlan": "{{ iscsiB_vlan_id }}",
         "AllowedVlans": "{{ iscsiB_vlan_id|int }}"
         }
      }
  register: iscsi_nvme_b_network_group_policy
  
- name: "Add NVMe-TCP-B VLAN to iSCSI-NVMe-TCP-B Network Group Policy"
  vars:
    api_info: &api_info_iscsi_b_w_nvme_tcp_b
      api_private_key: "{{ api_private_key }}"
      api_key_id: "{{ api_key_id }}"
      api_uri: "{{ api_uri | default(omit) }}"
      validate_certs: "{{ validate_certs | default(omit) }}"
      state: "{{ state | default(omit) }}"

  cisco.intersight.intersight_rest_api:
    <<: *api_info_iscsi_b_w_nvme_tcp_b
    resource_path: /fabric/EthNetworkGroupPolicies
    query_params:
       $filter: "Name eq '{{ name_of_network_group_policy_for_iscsi_nvme_tcp_b }}'"
    api_body: {
      "Name": "{{ name_of_network_group_policy_for_iscsi_nvme_tcp_b }}",
      "Description": "{{ description_of_network_group_policy_for_iscsi_nvme_tcp_b }}",

      "Organization": {
         "Moid": "{{ intersight_org.api_response.Moid }}"
       },
      Tags: [{Key: "configmode", Value: "ansible"},{Key: "prefix", Value: "{{ prefix }}"}],
      "VlanSettings": {
         "NativeVlan": "{{ iscsiB_vlan_id }}",
         "AllowedVlans": "{{ iscsiB_vlan_id }},{{ nvme_tcpB_vlan_id }}"
         }
      }
  when: configure_nvme_tcp == 'true'

- name: "Configure Ethernet Network Group Policy for NFS"
  vars:
    api_info: &api_info_nfs
      api_private_key: "{{ api_private_key }}"
      api_key_id: "{{ api_key_id }}"
      api_uri: "{{ api_uri | default(omit) }}"
      validate_certs: "{{ validate_certs | default(omit) }}"
      state: "{{ state | default(omit) }}"

  cisco.intersight.intersight_rest_api:
    <<: *api_info_nfs
    resource_path: /fabric/EthNetworkGroupPolicies
    query_params:
       $filter: "Name eq '{{ name_of_network_group_policy_for_nfs}}'"
    api_body: {
      "Name": "{{ name_of_network_group_policy_for_nfs }}",
      "Description": "{{ description_of_network_group_policy_for_nfs }}",

      "Organization": {
         "Moid": "{{ intersight_org.api_response.Moid }}"
       },
      Tags: [{Key: "configmode", Value: "ansible"},{Key: "prefix", Value: "{{ prefix }}"}],
      "VlanSettings": {
         "NativeVlan": "{{ nfs_vlan_id }}",
         "AllowedVlans": "{{ nfs_vlan_id|int }}"
         }
      }
  register: nfs_network_group_policy
  when: configure_nfs == 'true'
