---
#Execute the below ONTAP Role after Nexus playbook
- name: Configure ONTAP for FlexPod
  hosts: ontap
  gather_facts: False
  vars_files:
    - group_vars/secrets.yml
    - vars/ontap_main.yml
    - group_vars/all.yml
  connection: local
  roles:
  - { role: ONTAP/ontap_network, tags: [ 'ontap_network' ] }
  - { role: ONTAP/ontap_svm, tags: [ 'ontap_svm' ] }
  - { role: ONTAP/ontap_volumes, tags: [ 'ontap_volumes' ] }
  - { role: ONTAP/ontap_lifs, tags: [ 'ontap_lifs' ] }
  - { role: ONTAP/ontap_finalize_setup, tags: [ 'ontap_finalize_setup' ] }
  tags:
  - ontap_config
  - flexpod_config
