---
# Gather various policy details which will be used to map policies to Server Profile Templates
#
# Get UUID Pool for Service Profile Template
- name: "Get UUID Pool Details"
  vars:
    api_info: &api_info_uuid
      api_private_key: "{{ api_private_key }}"
      api_key_id: "{{ api_key_id }}"
      api_uri: "{{ api_uri | default(omit) }}"
      validate_certs: "{{ validate_certs | default(omit) }}"
      state: "{{ state | default(omit) }}"

  cisco.intersight.intersight_rest_api:
      <<: *api_info_uuid
      resource_path: /uuidpool/Pools
      query_params:
         $filter: "Name eq '{{ name_of_uuid_pool }}'"

  register: uuid_pool_details

- name: "Get M8 BIOS Policy Details"
  vars:
    api_info: &api_info_m8_bios_policy
      api_private_key: "{{ api_private_key }}"
      api_key_id: "{{ api_key_id }}"
      api_uri: "{{ api_uri | default(omit) }}"
      validate_certs: "{{ validate_certs | default(omit) }}"
      state: "{{ state | default(omit) }}"

  intersight_rest_api:
    <<: *api_info_m8_bios_policy
    resource_path: /bios/Policies
    query_params:
      $filter: "Name eq '{{ name_of_m8_bios_policy }}'"
  register:  m8_bios_policy_details
  when: server_generation == "M8"

# Get M7 BIOS Policy Details for Service Profile Template
- name: "Get M7 BIOS Policy Details"
  vars:
    api_info: &api_info_bios_policy
      api_private_key: "{{ api_private_key }}"
      api_key_id: "{{ api_key_id }}"
      api_uri: "{{ api_uri | default(omit) }}"
      validate_certs: "{{ validate_certs | default(omit) }}"
      state: "{{ state | default(omit) }}"

  intersight_rest_api:
    <<: *api_info_bios_policy
    resource_path: /bios/Policies
    query_params:
      $filter: "Name eq '{{ name_of_m7_bios_policy }}'"
  register:  m7_bios_policy_details
  when: server_generation == "M7"

- name: "Get M6 BIOS Policy Details"
  vars:
    api_info: &api_info_m6_bios_policy
      api_private_key: "{{ api_private_key }}"
      api_key_id: "{{ api_key_id }}"
      api_uri: "{{ api_uri | default(omit) }}"
      validate_certs: "{{ validate_certs | default(omit) }}"
      state: "{{ state | default(omit) }}"

  intersight_rest_api:
    <<: *api_info_m6_bios_policy
    resource_path: /bios/Policies
    query_params:
      $filter: "Name eq '{{ name_of_m6_bios_policy }}'"
  register:  m6_bios_policy_details
  when: server_generation == "M6" 

# Get M.2 Boot Order Policy for Service Profile Template
- name: "Get FC Boot Order Policy Details"
  vars:
    api_info: &api_info_m2_boot_policy
      api_private_key: "{{ api_private_key }}"
      api_key_id: "{{ api_key_id }}"
      api_uri: "{{ api_uri | default(omit) }}"
      validate_certs: "{{ validate_certs | default(omit) }}"
      state: "{{ state | default(omit) }}"

  intersight_rest_api:
    <<: *api_info_m2_boot_policy
    resource_path: /boot/PrecisionPolicies
    query_params:
      $filter: "Name eq '{{ m2_boot_order_policy_name }}'"
  register:  m2_boot_order_policy_details

# Get Server Power Policy for Service Profile Template
- name: "Get Server Power Policy Details"
  vars:
    api_info: &api_info_server_power_policy
      api_private_key: "{{ api_private_key }}"
      api_key_id: "{{ api_key_id }}"
      api_uri: "{{ api_uri | default(omit) }}"
      validate_certs: "{{ validate_certs | default(omit) }}"
      state: "{{ state | default(omit) }}"

  intersight_rest_api:
    <<: *api_info_server_power_policy
    resource_path: /power/Policies
    query_params:
      $filter: "Name eq '{{ server_power_policy_name }}'"
  register:  server_power_policy_details

# Get Server Thermal Policy for Service Profile Template
- name: "Get Server Thermal Policy Details"
  vars:
    api_info: &api_info_server_thermal_policy
      api_private_key: "{{ api_private_key }}"
      api_key_id: "{{ api_key_id }}"
      api_uri: "{{ api_uri | default(omit) }}"
      validate_certs: "{{ validate_certs | default(omit) }}"
      state: "{{ state | default(omit) }}"

  intersight_rest_api:
    <<: *api_info_server_thermal_policy
    resource_path: /thermal/Policies
    query_params:
      $filter: "Name eq '{{ server_thermal_policy_name }}'"
  register:  server_thermal_policy_details

# Get IMC Access Policy for Service Profile Template
- name: "Get IMC Access Policy Details"
  vars:
    api_info: &api_info_imc_access
      api_private_key: "{{ api_private_key }}"
      api_key_id: "{{ api_key_id }}"
      api_uri: "{{ api_uri | default(omit) }}"
      validate_certs: "{{ validate_certs | default(omit) }}"
      state: "{{ state | default(omit) }}"

  intersight_rest_api:
    <<: *api_info_imc_access
    resource_path: /access/Policies
    query_params:
      $filter: "Name eq '{{ name_of_imc_access_policy }}'"
  register:  imc_access_policy_details

# Get IPMI over LAN Policy for Service Profile Template
- name: "Get IPMI over LAN Policy Details"
  vars:
    api_info: &api_info_ipmi
      api_private_key: "{{ api_private_key }}"
      api_key_id: "{{ api_key_id }}"
      api_uri: "{{ api_uri | default(omit) }}"
      validate_certs: "{{ validate_certs | default(omit) }}"
      state: "{{ state | default(omit) }}"

  intersight_rest_api:
    <<: *api_info_ipmi
    resource_path: /ipmioverlan/Policies
    query_params:
      $filter: "Name eq '{{ name_of_ipmi_policy }}'"
  register:  ipmi_policy_details

# Get Local User Policy for Service Profile Template
- name: "Get Local User Policy Details"
  vars:
    api_info: &api_info_LocalUser
      api_private_key: "{{ api_private_key }}"
      api_key_id: "{{ api_key_id }}"
      api_uri: "{{ api_uri | default(omit) }}"
      validate_certs: "{{ validate_certs | default(omit) }}"
      state: "{{ state | default(omit) }}"

  intersight_rest_api:
    <<: *api_info_LocalUser
    resource_path: /iam/EndPointUserPolicies
    query_params:
      $filter: "Name eq '{{ name_of_LocalUser_policy }}'"
  register:  local_user_policy_details

# Get KVM Policy for Service Profile Template
- name: "Get KVM Policy Details"
  vars:
    api_info: &api_info_kvm
      api_private_key: "{{ api_private_key }}"
      api_key_id: "{{ api_key_id }}"
      api_uri: "{{ api_uri | default(omit) }}"
      validate_certs: "{{ validate_certs | default(omit) }}"
      state: "{{ state | default(omit) }}"

  intersight_rest_api:
    <<: *api_info_kvm
    resource_path: /kvm/Policies
    query_params:
      $filter: "Name eq '{{ name_of_kvm_policy }}'"
  register:  kvm_policy_details

# Get Virtual Media Policy for Service Profile Template
- name: "Get Virtual Media Policy Details"
  vars:
    api_info: &api_info_vmedia
      api_private_key: "{{ api_private_key }}"
      api_key_id: "{{ api_key_id }}"
      api_uri: "{{ api_uri | default(omit) }}"
      validate_certs: "{{ validate_certs | default(omit) }}"
      state: "{{ state | default(omit) }}"

  intersight_rest_api:
    <<: *api_info_vmedia
    resource_path: /vmedia/Policies
    query_params:
      $filter: "Name eq '{{ name_of_vmedia_policy }}'"
  register:  vmedia_policy_details

# Get M.2 RAID Storage Policy for Service Profile Template
- name: "Get M.2 Raid Storage Policy Details"
  vars:
    api_info: &api_info_m2raid
      api_private_key: "{{ api_private_key }}"
      api_key_id: "{{ api_key_id }}"
      api_uri: "{{ api_uri | default(omit) }}"
      validate_certs: "{{ validate_certs | default(omit) }}"
      state: "{{ state | default(omit) }}"

  intersight_rest_api:
    <<: *api_info_m2raid
    resource_path: /storage/StoragePolicies
    query_params:
      $filter: "Name eq '{{ name_of_m2_raid_policy }}'"
  register:  m2_raid_policy_details

# Get Control Plane Node LAN Connectivity Policy for Service Profile Template
- name: "Get Control Plane Node LAN Connectivity Policy Details"
  vars:
    api_info: &api_info_cp_lan_connectivity
      api_private_key: "{{ api_private_key }}"
      api_key_id: "{{ api_key_id }}"
      api_uri: "{{ api_uri | default(omit) }}"
      validate_certs: "{{ validate_certs | default(omit) }}"
      state: "{{ state | default(omit) }}"

  intersight_rest_api:
    <<: *api_info_cp_lan_connectivity
    resource_path: /vnic/LanConnectivityPolicies
    query_params:
      $filter: "Name eq '{{ name_of_cp_lan_connectivity_policy }}'"
  register:  cp_lan_connectivity_policy_details

# Get Worker Node LAN Connectivity Policy for Service Profile Template
- name: "Get Worker Node LAN Connectivity Policy Details"
  vars:
    api_info: &api_info_worker_lan_connectivity
      api_private_key: "{{ api_private_key }}"
      api_key_id: "{{ api_key_id }}"
      api_uri: "{{ api_uri | default(omit) }}"
      validate_certs: "{{ validate_certs | default(omit) }}"
      state: "{{ state | default(omit) }}"

  intersight_rest_api:
    <<: *api_info_worker_lan_connectivity
    resource_path: /vnic/LanConnectivityPolicies
    query_params:
      $filter: "Name eq '{{ name_of_worker_lan_connectivity_policy }}'"
  register:  worker_lan_connectivity_policy_details