---
# Create a new rule for the SVM NFS subnet in the default export policy
- name: Create a new rule for the OCP SVM NFS subnet in the default export policy
  netapp.ontap.na_ontap_export_policy_rule:
    state: present
    vserver: "{{item.svm_name}}"
    policy_name: default
    client_match: "{{item.client_match}}"
    protocol: "{{item.data_protocol}}"
    ro_rule: sys
    rw_rule: sys
    rule_index: 1
    super_user_security: sys
    allow_suid: true
    hostname: "{{inventory_hostname}}"
    username: "{{username}}"
    password: "{{password}}"
    https: true
    validate_certs: false
  with_items:
    - "{{tenant_specs}}"
  tags:
    - ontap_export_policy_rule

# Create FlexVol for storing SVM audit log configuration
- name: Create FlexVol for SVM audit log configuration
  netapp.ontap.na_ontap_volume:
    state: present
    vserver: "{{tenant_specs.svm_name}}"
    policy: default
    name: "{{tenant_specs.audit_log_volume_specs.name}}"
    aggregate_name: "{{tenant_specs.audit_log_volume_specs.residing_aggr}}"
    size: "{{tenant_specs.audit_log_volume_specs.size}}"
    is_online: true
    space_guarantee: none
    percent_snapshot_space: 0
    junction_path: /{{tenant_specs.audit_log_volume_specs.name}}
    hostname: "{{inventory_hostname}}"
    username: "{{username}}"
    password: "{{password}}"
    https: true
    validate_certs: false
  tags:
    - ontap_svm_audit_log_vol

# Get the SVM root volume information
- name: Get the SVM root volume information
  netapp.ontap.na_ontap_rest_info:
    hostname: "{{inventory_hostname}}"
    username: "{{username}}"
    password: "{{password}}"
    https: true
    validate_certs: false
    use_rest: always
    use_python_keys: true
    gather_subset:
      - volume_info
    parameters:
      name: "*root"
      svm.name: "{{tenant_specs.svm_name}}"
  register: svm_rootvol
  tags:
    - ontap_update_ls_mirrors

# Update set of load-sharing mirrors
- name: Update load-sharing mirrors
  netapp.ontap.na_ontap_rest_cli:
    command: 'snapmirror/update-ls-set'
    verb: 'POST'
    body: {'source-path': '{{tenant_specs.svm_name}}:{{svm_rootvol.ontap_info.storage_volumes.records[0].name}}'}
    hostname: "{{inventory_hostname}}"
    username: "{{username}}"
    password: "{{password}}"
    https: true
    validate_certs: false
  tags:
    - ontap_update_ls_mirrors
